### ISSUE TITLE
Playbook run successfully even when failed to install java sdk 

### ISSUE THREAD

**Issue by danielporto** [Comcast/ansible-sdkman#23] opened 2018-09-27 09:10 UTC
The playbook should fail when trying to install an unavailable version of the SDK. 

I ran a playbook which has an outdated and unavailable version of java sdk (8.0.163-zulu) and couldn't notice the sdk installation problem which I expected to be notified by the ansible role. The playbook completed without warnings or errors as if the installation was done successfully. All other playbooks that require the java sdk failed afterward.
 
Running from a Mac with target system: centos7 latest update baremetal. Python 2.7.
comcast/ansible-sdkman v1.4.1

Here is the playbook example:
- hosts: clients_cluster, leader, replicas
  become: no
  any_errors_fatal: true
  vars_files:
      - play-vars-ycsbsmart.yml

  roles:
    - role: comcast.sdkman
      sdkman_dir: "{{ sdkman_folder }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: "{{ java_version }}" }  # java_version: '8.0.163-zulu' unavailable
        - { candidate: ant, version: "{{ ant_version }}" }
      sdkman_flush_caches_before:
        - temp
      sdkman_flush_caches_after:
        - archives
        - broadcast
        - candidates
        - temp

  post_tasks:
    - name: Ensure presence of profile
      file: state=touch path=~/.profile

    - name: Add sdkman in .profile
      lineinfile: 
        path: ~/.profile 
        regexp: '\[\[ \-s \"{{sdkman_folder}}\/.*'
        line: '[[ -s "{{sdkman_folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman_folder}}/bin/sdkman-init.sh"'

    - name: Add sdkman in .bashrc
      lineinfile: 
        path: ~/.bashrc 
        regexp: '\[\[ \-s \"{{sdkman_folder}}\/.*'
        line: '[[ -s "{{sdkman_folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman_folder}}/bin/sdkman-init.sh"'

-----
playbook output:

PLAY [clients_cluster, leader, replicas, manager] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [Create environment folder] ****************************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=/home/goku/kaioken/data/wkld_characterization/centos7/ycsb)
ok: [capsulecorp_oc0] => (item=/home/goku/kaioken)
ok: [capsulecorp_oc0] => (item=/home/goku/kaioken/keys)

TASK [Copy default tmux] ************************************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [Define that the init tasks was done.] *****************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

PLAY [clients_cluster, leader, replicas] ********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [comcast.sdkman : Install SDKMAN] **********************************************************************************************************************************************************************************************************************************
included: /Volumes/data/Users/dan/.ansible/roles/comcast.sdkman/tasks/install.yml for capsulecorp_oc0

TASK [comcast.sdkman : Determine SDKMAN vars] ***************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [comcast.sdkman : Include system vars] *****************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=/Volumes/data/Users/dan/.ansible/roles/comcast.sdkman/vars/RedHat.yml)

TASK [comcast.sdkman : Install system packages] *************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=curl)
ok: [capsulecorp_oc0] => (item=findutils)
ok: [capsulecorp_oc0] => (item=libselinux-python)
ok: [capsulecorp_oc0] => (item=libstdc++)
ok: [capsulecorp_oc0] => (item=tar)
ok: [capsulecorp_oc0] => (item=unzip)
ok: [capsulecorp_oc0] => (item=which)
ok: [capsulecorp_oc0] => (item=zip)

TASK [comcast.sdkman : Install GLIBC for Alpine Linux] ******************************************************************************************************************************************************************************************************************
skipping: [capsulecorp_oc0]

TASK [comcast.sdkman : Check for SDKMAN installation] *******************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [comcast.sdkman : Download SDKMAN] *********************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [comcast.sdkman : Run SDKMAN script] *******************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [comcast.sdkman : Cleanup SDKMAN script] ***************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [comcast.sdkman : Fix permissions on SDKMAN_DIR] *******************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [comcast.sdkman : Run SDKMAN tasks] ********************************************************************************************************************************************************************************************************************************
included: /Volumes/data/Users/dan/.ansible/roles/comcast.sdkman/tasks/sdkman.yml for capsulecorp_oc0

TASK [comcast.sdkman : Configure SDKMAN] ********************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [comcast.sdkman : Flush SDK caches (before)] ***********************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=temp)

TASK [comcast.sdkman : Update SDKMAN] ***********************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0]

TASK [comcast.sdkman : Install SDK candidates/versions] *****************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0] => (item={u'version': u'8.0.163-zulu', u'candidate': u'java'})
changed: [capsulecorp_oc0] => (item={u'version': u'1.10.1', u'candidate': u'ant'})

TASK [comcast.sdkman : Uninstall SDK candidates/versions] ***************************************************************************************************************************************************************************************************************

TASK [comcast.sdkman : Get SDK defaults] ********************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=ant)
ok: [capsulecorp_oc0] => (item=java)

TASK [comcast.sdkman : Set SDK defaults] ********************************************************************************************************************************************************************************************************************************

TASK [comcast.sdkman : Flush SDK caches (after)] ************************************************************************************************************************************************************************************************************************
ok: [capsulecorp_oc0] => (item=archives)
ok: [capsulecorp_oc0] => (item=broadcast)
ok: [capsulecorp_oc0] => (item=candidates)
ok: [capsulecorp_oc0] => (item=temp)

TASK [Ensure presence of profile] ***************************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [Add sdkman in .profile] *******************************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

TASK [Add sdkman in .bashrc] ********************************************************************************************************************************************************************************************************************************************
changed: [capsulecorp_oc0]

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************
capsulecorp_oc0                  : ok=24   changed=9    unreachable=0    failed=0

**Comment by elliotweiser** [comment] 2018-09-27 15:59
This is actually a bug in SDKMAN itself. FWIW, `sdk install java nonexistent` will have an exit code of 0 (`echo $?`).

Reported it here: https://github.com/sdkman/sdkman-cli/issues/665
Fixed it here: https://github.com/sdkman/sdkman-cli/pull/666

He has yet to release the fix, so I'll go remind him...

Since there's not much that can be done from this end, I'm going to close this. Also this is a duplicate of #19.

**Closed by elliotweiser** 2018-09-27 15:59 UTC

**Comment by elliotweiser** [comment] 2018-09-28 16:59
@danielporto SDKMAN 5.7.3 is released and contains the fix. You should see non-zero exit codes when attempting to install non-existent packages.
